project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://yuer0604.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-depth: 2
    number-sections: true

editor:
  mode: source
